import { expect, test } from "./support/coverage"
import { ensureJobSearchWorkspace } from "./support/workspaces"

test("Given several boards, when searching discovery, then title, owner, filters, and empty state stay clear", async ({ page }) => {
  await page.goto("/")
  await ensureJobSearchWorkspace(page)
  await expect(page.locator(".active-board-owner")).toContainText("Owner:")
  await page.getByRole("button", { name: "Open workspaces" }).click()
  const dialog = page.getByRole("dialog", { name: "Workspaces" })
  await expect(dialog.getByRole("heading", { name: "Recent" })).toHaveCount(0)
  await dialog.getByRole("searchbox", { name: "Search boards" }).fill("job")
  await expect(dialog.locator(".workspace-item")).toHaveCount(1)
  await expect(dialog.locator(".workspace-item").first()).toContainText("Owner:")
  const ownerName = (await page.locator(".active-board-owner").textContent())?.replace("Owner:", "").trim() ?? ""
  await dialog.getByRole("searchbox", { name: "Search boards" }).fill(ownerName)
  await expect(dialog.locator(".workspace-item")).toHaveCount(2)
  await dialog.getByRole("searchbox", { name: "Search boards" }).fill("no-board-matches-this")
  await expect(dialog.getByRole("status")).toHaveText("No boards match this search.")
  await expect(dialog.locator(".workspace-item")).toHaveCount(0)
  await dialog.getByRole("searchbox", { name: "Search boards" }).fill("")
  await dialog.getByRole("button", { name: "Mine" }).click()
  await expect(dialog.locator(".workspace-item")).toHaveCount(2)
  await dialog.getByRole("button", { name: "Shared" }).click()
  await expect(dialog.locator(".workspace-item")).toHaveCount(0)
  await dialog.getByRole("button", { name: "All boards" }).click()
  await dialog.getByRole("button", { name: "Pin Job search" }).click()
  await expect(dialog.getByRole("region", { name: "Pinned boards" })).toContainText("jobs")
  await dialog.getByRole("button", { name: "New workspace" }).click()
  const createDialog = page.getByRole("dialog", { name: "Create workspace" })
  await createDialog.getByLabel("Title", { exact: true }).fill("Reading list")
  await createDialog.getByRole("button", { name: "Create", exact: true }).click()
  await expect(page.getByRole("region", { name: "Reading list", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Open workspaces" }).click()
  const updatedDialog = page.getByRole("dialog", { name: "Workspaces" })
  await updatedDialog.getByRole("button", { name: "Pin Reading list" }).click()
  const pinned = updatedDialog.getByRole("region", { name: "Pinned boards" })
  await expect(pinned.locator(".directory-row")).toHaveCount(2)
  await pinned.getByRole("button", { name: "Move Reading list up" }).click()
  await expect(pinned.locator(".directory-link").first()).toContainText("Reading list")
  await expect(pinned.locator(".directory-row").allTextContents()).resolves.toHaveLength(2)
  await expect(updatedDialog.locator(".board-directory h3").first()).toHaveText("Pinned")
  await updatedDialog.locator(".workspace-switch").filter({ hasText: "jobs" }).click()
  await page.getByRole("button", { name: "Open workspaces" }).click()
  const returnedDialog = page.getByRole("dialog", { name: "Workspaces" })
  await expect(returnedDialog.getByRole("heading", { name: "Recent" })).toBeVisible()
  await expect(returnedDialog.getByRole("region", { name: "Recent boards" })).toContainText("jobs")
})

test("Given empty workspace chat, when opened, then message area owns scrolling without a stray content scrollbar", async ({ page }) => {
  await page.goto("/")
  await ensureJobSearchWorkspace(page)
  await page.getByRole("button", { name: "Workspace chat" }).last().click()
  const dialog = page.locator(".spatial-window:has(.chat-dialog)")
  await expect(dialog.locator(".chat-messages-log")).toContainText("No messages yet. Send a message to start chatting.")
  const scrollBehavior = await dialog.evaluate(element => {
    const outer = element.querySelector<HTMLElement>(".spatial-body")!
    const inner = element.querySelector<HTMLElement>(".chat-messages-log")!
    return { outerOverflow: getComputedStyle(outer).overflowY, innerOverflow: getComputedStyle(inner).overflowY, outerFits: outer.scrollHeight <= outer.clientHeight }
  })
  expect(scrollBehavior).toEqual({ outerOverflow: "auto", innerOverflow: "auto", outerFits: true })
  await expect(dialog.getByRole("textbox", { name: "Message" })).toBeVisible()
  await dialog.getByRole("textbox", { name: "Message" }).fill(Array.from({ length: 110 }, () => "Long chat entry").join("\n"))
  await dialog.getByRole("button", { name: "Send message" }).click()
  await expect.poll(() => dialog.locator(".chat-messages-log").evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true)
})
