import { expect, test } from "./support/coverage"
import { createJobSearchWorkspace } from "./support/workspaces"

for (const width of [390, 1440]) {
  test(`Given ${width}px board and fit score, when Discuss appears on hover or focus then score stays readable and only saved messages add a count on the icon`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto("/")
    await createJobSearchWorkspace(page, "Card controls")
    await page.getByRole("button", { name: "Add lead to Lead", exact: true }).click()
    const form = page.getByRole("dialog", { name: "Add item" })
    await form.getByLabel("Company *").fill("Reedsy")
    await form.getByLabel("Role *").fill("Senior Ruby Engineer")
    await form.getByLabel("Location", { exact: true }).fill("Remote Europe")
    await form.getByLabel("Fit score").fill("8")
    await form.getByRole("button", { name: "Create item" }).click()
    const details = page.getByRole("dialog", { name: "Lead details" })
    await details.getByRole("button", { name: "Close detail", exact: true }).click()
    const card = page.locator(".item-card").filter({ hasText: "Reedsy" })
    const discuss = card.getByRole("button", { name: /Discuss Reedsy/ })
    for (const activate of [() => card.hover(), () => discuss.focus()]) {
      await activate()
      await expect(discuss).toHaveCSS("opacity", "1")
      const fit = (await card.locator(".fit").boundingBox())!
      const button = (await discuss.boundingBox())!
      expect(fit.x + fit.width + 4).toBeLessThanOrEqual(button.x)
      expect(await card.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    }
    const initialHeight = await card.evaluate(element => element.clientHeight)
    await card.screenshot({ path: info.outputPath(`card-controls-${width}.png`) })
    await discuss.click()
    const discussion = page.getByRole("dialog", { name: /^Discussion · Reedsy/ })
    await expect(card.locator(".has-discussion")).toHaveCount(0)
    await expect(details).toHaveCount(0)
    await expect(discussion.getByRole("button", { name: "Send message", exact: true })).toBeDisabled()
    await discussion.getByRole("textbox", { name: "Message", exact: true }).fill("Unsent card question")
    await discussion.getByRole("button", { name: "Close", exact: true }).click()
    await expect(card.locator(".card-discussion-count")).toHaveCount(0)
    await discuss.focus()
    await discuss.click()
    await expect(discussion.getByRole("textbox", { name: "Message", exact: true })).toHaveValue("Unsent card question")
    await discussion.getByRole("button", { name: "Send message", exact: true }).click()
    await expect(discussion.getByText("Unsent card question", { exact: true })).toBeVisible()
    await discussion.getByRole("button", { name: "Close", exact: true }).click()
    await page.getByRole("heading", { name: "Lead", exact: true }).click()
    const existingDiscussion = card.getByRole("button", { name: /Open discussion for Reedsy/ })
    await expect(existingDiscussion).toHaveCSS("opacity", "1")
    const badge = existingDiscussion.locator(".card-discussion-count")
    await expect(badge).toHaveText("1")
    await expect(card).not.toContainText("Unsent card question")
    expect(await card.evaluate(element => element.clientHeight)).toBe(initialHeight)
    await card.screenshot({ path: info.outputPath(`card-existing-discussion-${width}.png`) })
    await page.reload()
    await expect(badge).toHaveText("1")
    await expect(existingDiscussion).toBeVisible()
    await existingDiscussion.click()
    const thread = page.getByRole("dialog", { name: "Discussion · replies", exact: true })
    await expect(discussion).toHaveCount(0)
    await expect(page.getByRole("dialog", { name: "Workspace chat", exact: true })).toHaveCount(0)
    await expect(thread.getByText("Unsent card question", { exact: true })).toBeVisible()
    await thread.getByRole("textbox", { name: "Message", exact: true }).fill("Latest saved reply")
    await thread.getByRole("button", { name: "Send message", exact: true }).click()
    await expect(thread.getByText("Latest saved reply", { exact: true })).toBeVisible()
    await thread.getByRole("button", { name: "Close", exact: true }).click()
    await expect(badge).toHaveText("2")
    await expect(card).not.toContainText("Latest saved reply")
    expect(await card.evaluate(element => element.clientHeight)).toBe(initialHeight)
    await page.reload()
    await existingDiscussion.click()
    await expect(thread.locator(".chat-message-item")).toHaveCount(2)
    await expect(thread.getByRole("button", { name: "Reply to message" })).toHaveCount(0)
    const saved = await page.evaluate(async () => {
      const service = await import("/src/chat/service.ts")
      const state = (await import("/src/state.ts")).useTincanban()
      return (await service.loadChat(state.activeWorkspace.id)).messages
    })
    const root = saved.find(message => message.body === "Unsent card question")!
    const reply = saved.find(message => message.body === "Latest saved reply")!
    expect(reply.context?.replyTo).toBe(root.id)
    expect(reply.context?.conversationRootId).toBe(root.id)
  })
}
