import { expect, test } from "./support/coverage"
import { createJobSearchWorkspace } from "./support/workspaces"

for (const width of [390, 1440]) {
  test(`Given ${width}px chat and many reference kinds, when typing and filtering then compact examples become matching references and empty search recovers`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 1000 })
    await page.goto("/")
    await createJobSearchWorkspace(page, "Reference search")
    for (const company of ["Reedsy", "Cleo", "Missive"]) {
      await page.getByRole("button", { name: "Add lead to Lead", exact: true }).click()
      const form = page.getByRole("dialog", { name: "Add item" })
      await form.getByLabel("Company *").fill(company)
      await form.getByLabel("Role *").fill("Ruby Engineer")
      await form.getByLabel("Description", { exact: true }).fill(`Hiring notes for ${company}`)
      await form.getByLabel("Location", { exact: true }).fill("Remote Europe")
      await form.getByLabel("Fit score").fill("8")
      await form.getByRole("button", { name: "Create item" }).click()
      await page.getByRole("dialog", { name: "Lead details" }).getByRole("button", { name: "Close detail", exact: true }).click()
    }
    await page.getByRole("button", { name: "Workspace chat", exact: true }).filter({ visible: true }).click()
    const chat = page.getByRole("dialog", { name: "Workspace chat", exact: true })
    await chat.getByText("Attach item reference", { exact: true }).click()
    const picker = chat.locator(".reference-picker")
    const search = picker.getByRole("searchbox", { name: "Find reference", exact: true })
    await expect(search).toBeFocused()
    const results = picker.getByRole("list", { name: "Reference matches" })
    await expect(results.getByRole("button")).toHaveCount(6)
    await expect(results).toContainText("Card")
    await expect(results).toContainText("Description")
    await expect(results).toContainText("Field")
    await search.fill("cLeO")
    await picker.getByRole("button", { name: "Cards", exact: true }).click()
    await expect(results.getByRole("button")).toHaveCount(1)
    await results.getByRole("button", { name: "Cleo — Ruby Engineer", exact: true }).click()
    await expect(chat.locator(".reference-chips").getByRole("button", { name: "Cleo — Ruby Engineer", exact: true })).toBeVisible()
    await picker.getByRole("button", { name: "Fields", exact: true }).click()
    await search.fill("reedsy fit")
    await expect(results.getByRole("button")).toHaveCount(1)
    await results.getByRole("button").click()
    await expect(results.getByRole("button")).toBeDisabled()
    await search.fill("no such reference")
    await expect(results.getByRole("button")).toHaveCount(0)
    await expect(picker.getByRole("status")).toHaveText("No references match this search.")
    await search.fill("engineer")
    await picker.getByRole("button", { name: "All", exact: true }).click()
    expect(await results.getByRole("button").count()).toBeLessThanOrEqual(8)
    await chat.screenshot({ path: info.outputPath(`reference-picker-${width}.png`) })
    await chat.getByRole("textbox", { name: "Message", exact: true }).fill("Two searched references")
    await chat.getByRole("button", { name: "Send message", exact: true }).click()
    const saved = chat.locator(".chat-message-item").filter({ hasText: "Two searched references" })
    await expect(saved.locator(".reference-chips button")).toHaveCount(2)
    expect(await chat.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  })
}
