import { discussObject } from "./support/discussions"
import { expect, test } from "./support/coverage"
import { createJobSearchWorkspace } from "./support/workspaces"

async function board(page: import("@playwright/test").Page) {
  await page.goto("/")
  await createJobSearchWorkspace(page, "Context entry points")
  await page.getByRole("button", { name: "Add lead to Lead", exact: true }).click()
  const form = page.getByRole("dialog", { name: "Add item" })
  await form.getByLabel("Company *").fill("Reedsy")
  await form.getByLabel("Role *").fill("Senior Ruby Engineer")
  await form.getByLabel("Location", { exact: true }).fill("Remote Europe")
  await form.getByRole("button", { name: "Create item" }).click()
  await expect(form).toBeHidden()
  return page.getByRole("dialog", { name: "Lead details" })
}

test("Given board card, when Discuss sends then source link opens card and workspace Reply opens a thread", async ({ page }) => {
  const item = await board(page)
  await item.getByRole("button", { name: "Close detail", exact: true }).click()
  const card = page.locator(".item-card").filter({ hasText: "Reedsy" })
  await card.hover()
  await card.getByRole("button", { name: /Discuss Reedsy/ }).click()
  await expect(item).toHaveCount(0)
  const discussion = page.getByRole("dialog", { name: /^Discussion · Reedsy/ })
  await discussion.getByRole("textbox", { name: "Message", exact: true }).fill("Check this role")
  await discussion.getByRole("button", { name: "Send message" }).click()
  await expect(discussion.getByText("Saving locally…", { exact: true })).toHaveCount(0)
  await discussion.locator(".chat-message-item .reference-chips button").click()
  await expect(item).toBeVisible()
  await item.getByRole("button", { name: "Close detail", exact: true }).click()
  await discussion.getByRole("button", { name: "Close", exact: true }).click()
  await page.getByRole("button", { name: "Workspace chat", exact: true }).filter({ visible: true }).click()
  const chat = page.getByRole("dialog", { name: "Workspace chat", exact: true })
  await chat.getByRole("button", { name: "Reply to message" }).click()
  const thread = page.getByRole("dialog", { name: "Discussion · replies", exact: true })
  await expect(thread.locator(".reply-quote")).toHaveCount(0)
  await expect(thread.getByRole("button", { name: "Open thread" })).toHaveCount(0)
  await thread.getByRole("textbox", { name: "Message", exact: true }).fill("Check remote terms")
  await thread.getByRole("button", { name: "Send message" }).click()
  await expect(thread.getByText("Saving locally…", { exact: true })).toHaveCount(0)
  await expect(thread.locator(".chat-message-item")).toHaveCount(2)
  await thread.getByRole("button", { name: "Close", exact: true }).click()
  await expect(chat.locator(".chat-message-item")).toHaveCount(1)
  await expect(chat.getByRole("button", { name: "Reply to message" })).toHaveCount(0)
  await expect(chat.getByRole("button", { name: "1 reply", exact: true })).toHaveCount(1)
  await expect(chat.getByRole("button", { name: "Open separately" })).toHaveCount(0)
  await chat.getByRole("button", { name: "1 reply", exact: true }).click()
  await expect(thread.locator(".chat-message-item")).toHaveCount(2)
  await expect(thread.getByRole("button", { name: "Reply to message" })).toHaveCount(0)
  await expect(thread.locator(".reply-quote")).toHaveCount(0)
  for (const body of ["Second thread reply", "Third thread reply"]) {
    await thread.getByRole("textbox", { name: "Message", exact: true }).fill(body)
    await thread.getByRole("button", { name: "Send message" }).click()
    await expect(thread.getByText("Saving locally…", { exact: true })).toHaveCount(0)
    await expect(thread.locator(".chat-message-body").getByText(body, { exact: true })).toBeVisible()
    await expect(thread.getByRole("textbox", { name: "Message", exact: true })).toBeFocused()
  }
  await expect(thread.locator(".chat-message-item")).toHaveCount(4)
  await thread.getByRole("button", { name: "Close", exact: true }).click()
  await expect(chat.getByRole("button", { name: "3 replies", exact: true })).toHaveCount(1)
  await expect(thread.locator(".chat-message-item .reply-quote")).toHaveCount(0)
})

test("Given lead metadata selection spanning fields, when Discuss then captured quote attaches and returns to source", async ({ page }) => {
  const item = await board(page)
  await item.locator(".detail-grid").evaluate(el => {
    const range = document.createRange()
    range.selectNodeContents(el)
    const selection = window.getSelection()!
    selection.removeAllRanges()
    selection.addRange(range)
    document.dispatchEvent(new Event("selectionchange"))
  })
  await page.getByRole("button", { name: "Discuss selection", exact: true }).click()
  const discussion = page.getByRole("dialog", { name: /^Discussion/ })
  await expect(discussion.locator(".draft-reference")).toContainText("Remote Europe")
  await discussion.getByRole("textbox", { name: "Message", exact: true }).fill("Review these fields")
  await discussion.getByRole("button", { name: "Send message" }).click()
  await expect(discussion.getByText("Saving locally…", { exact: true })).toHaveCount(0)
  await discussion.locator(".chat-message-item .reference-chips button").click()
  await expect(item.locator("mark")).toContainText("Remote Europe")
})

test("Given board text, when pointer selects company then Discuss opens quote without opening card", async ({ page }) => {
  const item = await board(page)
  await item.getByRole("button", { name: "Close detail", exact: true }).click()
  const company = page.locator(".item-card .company").filter({ hasText: "Reedsy" })
  const bounds = (await company.boundingBox())!
  await page.mouse.move(bounds.x + 1, bounds.y + bounds.height / 2)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width - 1, bounds.y + bounds.height / 2, { steps: 8 })
  await page.mouse.up()
  await expect(item).toHaveCount(0)
  await page.getByRole("button", { name: "Discuss selection", exact: true }).click()
  const discussion = page.getByRole("dialog", { name: /^Discussion/ })
  await expect(discussion.locator(".draft-reference")).toContainText("Reedsy")
  await discussion.locator(".draft-reference button").first().click()
  await expect(item).toBeVisible()
  await expect(item.locator("h2 mark")).toHaveText("Reedsy")
  await expect(item.getByRole("button", { name: "Discuss", exact: true })).toHaveCount(0)
})

test("Given card context menu, when right click then native menu is suppressed and Escape dismisses app menu", async ({ page }) => {
  const item = await board(page)
  await item.getByRole("button", { name: "Close detail", exact: true }).click()
  await page.evaluate(() => document.addEventListener("contextmenu", event => {
    document.body.dataset.nativeMenuSuppressed = String(event.defaultPrevented)
  }))
  const card = page.locator(".item-card").filter({ hasText: "Reedsy" })
  await card.click({ button: "right", position: { x: 4, y: 4 } })
  await expect(page.locator("body")).toHaveAttribute("data-native-menu-suppressed", "true")
  const menu = page.getByRole("menu", { name: "Discussion actions" })
  await expect(menu).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(menu).toHaveCount(0)
  await expect(page.getByRole("dialog", { name: /^Discussion/ })).toHaveCount(0)
  await card.click({ button: "right", position: { x: 4, y: 4 } })
  await page.getByRole("menuitem", { name: "Discuss", exact: true }).click()
  await expect(page.getByRole("dialog", { name: /^Discussion/ }).locator(".draft-reference")).toContainText("Reedsy")
})

test("Given window controls, when maximize restore and cycle then fixed SVG controls keep header reachable", async ({ page }) => {
  await page.setViewportSize({ width: 1024, height: 768 })
  const item = await board(page)
  const controls = item.locator(".spatial-controls")
  await expect(controls.locator("button svg")).toHaveCount(2)
  await expect(controls).toHaveText("")
  await item.getByRole("button", { name: "Maximize window", exact: true }).click()
  const heading = item.locator(".spatial-heading")
  expect(await heading.evaluate(el => el.scrollHeight <= el.clientHeight)).toBe(true)
  await item.getByRole("button", { name: "Restore window size", exact: true }).click()
  await discussObject(page, item)
  const discussion = page.getByRole("dialog", { name: /^Discussion/ })
  await expect(discussion.getByRole("textbox", { name: "Message", exact: true })).toBeFocused()
  await discussion.locator(".spatial-titlebar").focus()
  await page.keyboard.press("Alt+Backquote")
  await expect(item).toBeFocused()
})
