import { expect, test } from "./support/coverage"
test("Given an active Rusty integration, when owner disables future boards, then current access remains active", async ({ page }) => {
  await page.goto("/")
  await page.evaluate(async () => (await import("/e2e/support/keeperSettings.ts")).mountKeeperSettings())
  const list = page.getByRole("list", { name: "Keeper services" })
  await list.getByRole("button", { name: /Rusty keeper/ }).click()
  await page.getByRole("button", { name: "Manage board access" }).click()
  await expect(page.getByRole("checkbox", { name: "Include future boards" })).toBeChecked()
  await page.getByRole("checkbox", { name: "Include future boards" }).uncheck()
  await page.getByRole("button", { name: "Save future-board setting" }).click()
  await expect(page.getByRole("status", { name: "Keeper settings status" })).toContainText("Future boards are off. Current board access remains active.")
  await expect(page.getByText("Current board", { exact: true })).toBeVisible()
  await expect(page.getByText("Existing unselected board", { exact: true })).toHaveCount(0)
})

test("Given an active Rusty integration, when settings save hits a stale revision, then old scopes stay visible and retry remains available", async ({ page }) => {
  await page.goto("/")
  await page.evaluate(async () => (await import("/e2e/support/keeperSettings.ts")).mountKeeperSettings("error"))
  await page.getByRole("list", { name: "Keeper services" }).getByRole("button", { name: /Rusty keeper/ }).click()
  await page.getByRole("button", { name: "Manage board access" }).click()
  await page.getByRole("checkbox", { name: "Include future boards" }).uncheck()
  await page.getByRole("button", { name: "Save future-board setting" }).click()
  await expect(page.getByRole("alert", { name: "Keeper settings error" })).toContainText("Integration revision changed")
  await expect(page.getByRole("status", { name: "Keeper settings status" })).toContainText("Current access remains active")
  await expect(page.getByRole("button", { name: "Retry settings update" })).toBeVisible()
  await expect(page.getByText("Current board", { exact: true })).toBeVisible()
})

test("Given future boards are off, when owner enables them, then policy-only request asks both sides to approve without rejoining current boards", async ({ page }) => {
  await page.goto("/")
  await page.evaluate(async () => (await import("/e2e/support/keeperSettings.ts")).mountKeeperSettings("off"))
  await page.getByRole("list", { name: "Keeper services" }).getByRole("button", { name: /Rusty keeper/ }).click()
  await page.getByRole("button", { name: "Manage board access" }).click()
  await expect(page.getByRole("checkbox", { name: "Include future boards" })).not.toBeChecked()
  await page.getByRole("checkbox", { name: "Include future boards" }).check()
  await page.getByRole("button", { name: "Request future-board approval" }).click()
  await expect(page.getByText("518407")).toBeVisible()
  await expect(page.getByText("Both the operator and owner must approve this code before future-board policy changes.")).toBeVisible()
  await expect(page.getByRole("status", { name: "Current integration access" })).toContainText("Current access stays active: Current board")
  await expect(page.getByRole("checkbox", { name: "Keeper board: Current board" })).toHaveCount(0)
  await page.getByRole("button", { name: "Code matches · approve" }).click()
  await expect(page.getByText("Future boards enabled. Current board access remains active.")).toBeVisible()
  await expect(page.getByRole("status", { name: "Current integration access" })).toContainText("Current board")
})

test("Given the last board scope is gone, when owner reloads keeper list, then settings and manual board approval remain available", async ({ page }) => {
  await page.goto("/")
  await page.evaluate(async () => (await import("/e2e/support/keeperSettings.ts")).mountKeeperSettings("empty"))
  const list = page.getByRole("list", { name: "Keeper services" })
  const keeper = list.getByRole("button", { name: /Rusty keeper/ })
  await expect(keeper).toContainText("No boards · not connected to this board")
  await keeper.click()
  await page.getByRole("button", { name: "Manage board access" }).click()
  await page.getByRole("checkbox", { name: "Include future boards" }).check()
  await page.getByRole("button", { name: "Request future-board approval" }).click()
  await expect(page.getByRole("status", { name: "Current integration access" })).toContainText("no active boards")
  await page.getByRole("button", { name: "Code matches · approve" }).click()
  await expect(page.getByText("Future boards enabled. No board access added.")).toBeVisible()
  await page.getByRole("button", { name: "Back" }).click()
  await page.getByRole("button", { name: /Add keeper/ }).click()
  await page.getByRole("textbox", { name: "Keeper hostname" }).fill("http://127.0.0.1:4244")
  await page.getByRole("button", { name: "Discover keeper" }).click()
  await expect(page.getByRole("checkbox", { name: "Keeper board: New board" })).toBeChecked()
  await page.getByRole("checkbox", { name: "Keeper board: Current board" }).uncheck()
  await page.getByRole("checkbox", { name: "Keeper board: Existing unselected board" }).uncheck()
  await page.getByRole("button", { name: "Request access" }).click()
  await expect(page.getByText("611204")).toBeVisible()
  await expect(page.getByRole("checkbox", { name: "Keeper board: New board" })).toBeChecked()
})

test("Given old Rusty lacks signed settings capability, when owner opens keeper, then settings stay unavailable but new-board pairing works", async ({ page }) => {
  await page.goto("/")
  await page.evaluate(async () => (await import("/e2e/support/keeperSettings.ts")).mountKeeperSettings("unsupported"))
  await page.getByRole("list", { name: "Keeper services" }).getByRole("button", { name: /Rusty keeper/ }).click()
  await expect(page.getByText("Board settings require a newer Rusty version.")).toBeVisible()
  await expect(page.getByRole("button", { name: "Manage board access" })).toHaveCount(0)
  await page.getByRole("button", { name: "Back" }).click()
  await page.getByRole("button", { name: /Add keeper/ }).click()
  await page.getByRole("textbox", { name: "Keeper hostname" }).fill("http://127.0.0.1:4244")
  await page.getByRole("button", { name: "Discover keeper" }).click()
  await page.getByRole("checkbox", { name: "Keeper board: Existing unselected board" }).uncheck()
  await page.getByRole("button", { name: "Request access" }).click()
  await expect(page.getByText("611204")).toBeVisible()
})

test("Given a saved unresolved cancellation outbox, when owner opens keeper list, then no history row resurfaces and adding remains available", async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 800 })
  await page.goto("/")
  await page.evaluate(async () => (await import("/e2e/support/keeperSettings.ts")).mountKeeperSettings("pending"))
  await expect(page.getByRole("region", { name: "Saved keeper cancellation history" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Add keeper" })).toBeEnabled()
  const retained = await page.evaluate(async () => (await import("/src/sync/ownerKeeper.ts")).pendingKeeperWithdrawals())
  expect(retained).toHaveLength(1)

  await page.getByRole("button", { name: "Add keeper" }).click()
  await page.getByRole("textbox", { name: "Keeper hostname" }).fill("http://127.0.0.1:4244")
  await page.getByRole("button", { name: "Discover keeper" }).click()
  await page.getByRole("button", { name: "Request access" }).click()
  await expect(page.getByRole("alert")).toContainText("still needs cleanup")
  expect(await page.evaluate(() => (window as unknown as { keeperPairingRequest?: unknown }).keeperPairingRequest)).toBeUndefined()

  await page.getByRole("button", { name: "Back" }).click()
  await page.getByRole("button", { name: "Add keeper" }).click()
  await page.getByRole("textbox", { name: "Keeper hostname" }).fill("http://127.0.0.1:4245")
  await page.getByRole("button", { name: "Discover keeper" }).click()
  await page.getByRole("button", { name: "Request access" }).click()
  await expect(page.getByText("Waiting for both approvals. No access granted.")).toBeVisible()
  expect(await page.evaluate(() => (window as unknown as { keeperPairingRequest?: { origin?: string } }).keeperPairingRequest?.origin))
    .toBe("http://127.0.0.1:4245")
  expect(await page.evaluate(async () => (await import("/src/sync/ownerKeeper.ts")).pendingKeeperWithdrawals())).toHaveLength(1)
})

test("Given a saved active keeper, when verified removal succeeds, then row stays absent after reload", async ({ page }) => {
  await page.goto("/")
  await page.evaluate(async () => (await import("/e2e/support/keeperSettings.ts")).mountKeeperSettings("remove"))
  const list = page.getByRole("list", { name: "Keeper services" })
  const keeper = list.getByRole("button", { name: /Rusty keeper/ })
  await keeper.click()
  await page.getByRole("button", { name: "Remove keeper" }).click()
  await page.getByRole("button", { name: "Remove access from all boards" }).click()
  await expect(list.getByRole("button", { name: /Rusty keeper/ })).toHaveCount(0)
  await expect(page.getByText("No keepers connected to this board.")).toBeVisible()
  await page.reload()
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  await expect(page.getByRole("list", { name: "Keeper services" })).toHaveCount(0)
  await expect(page.getByText("No keepers connected to this board.")).toBeVisible()
})

for (const scenario of [
  { mode: "availability-available" as const, expected: "Keeper · Service available", dot: "service-available", width: 1280, screenshot: "keeper-service-available-desktop.png" },
  { mode: "availability-unavailable" as const, expected: "Keeper · Service unreachable", dot: "service-unavailable", width: 360, screenshot: "keeper-service-unreachable-mobile.png" },
  { mode: "availability-needs-review" as const, expected: "Keeper · Status needs review", dot: "service-checking", width: 1280, screenshot: "keeper-service-review-desktop.png" },
]) {
  test(`Given saved Rusty integration, when signed status is ${scenario.mode}, then UI separates service state from P2P presence`, async ({ page }) => {
    await page.setViewportSize({ width: scenario.width, height: 800 })
    await page.goto("/")
    await page.evaluate(async mode => (await import("/e2e/support/keeperSettings.ts")).mountKeeperSettings(mode, false), scenario.mode)
    if (scenario.width <= 768) {
      await page.getByRole("button", { name: "Menu" }).click()
      await page.getByRole("button", { name: "Sync, import & export" }).click()
    } else await page.getByRole("button", { name: "Sync", exact: true }).click()
    const dialog = page.getByRole("dialog", { name: "Device sync" })
    const list = dialog.getByRole("list", { name: "Keeper services" })
    const keeper = list.getByRole("button", { name: /Rusty keeper/ })
    await expect(keeper).toContainText(scenario.expected)
    await expect(keeper.locator(".keeper-dot")).toHaveAttribute("data-state", scenario.dot)
    await keeper.click()
    const detailStatus = dialog.getByText(scenario.expected, { exact: false }).last()
    await expect(detailStatus).toBeVisible()
    await expect(dialog.locator(".keeper-panel-head h3")).toHaveText("Rusty keeper")
    await dialog.screenshot({ path: test.info().outputPath(scenario.screenshot) })
  })
}
