import { expect, test } from "@playwright/test"
import { ensureJobSearchWorkspace } from "./support/workspaces"

test("owner promotes a visitor, then removes only their device through an explicit scope confirmation", async ({ page, browser }, testInfo) => {
  test.setTimeout(90000)
  await page.goto("/")
  await ensureJobSearchWorkspace(page)
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  const host = page.getByRole("dialog", { name: "Device sync" })
  await host.getByRole("button", { name: "Add someone" }).click()
  await host.getByRole("button", { name: "Generate link" }).click()
  const context = await browser.newContext()
  const guest = await context.newPage()
  await guest.goto(await host.getByLabel("Pairing link").inputValue())
  const guestDialog = guest.getByRole("dialog", { name: "Device sync" })
  await guestDialog.getByRole("button", { name: "Accept and join" }).click()
  await host.getByRole("button", { name: "Approve access" }).click()
  await expect(guestDialog.getByText(/Connected to/)).toBeVisible({ timeout: 30000 })
  await guestDialog.getByRole("button", { name: "Close", exact: true }).first().click()
  await host.getByRole("button", { name: "Close", exact: true }).first().click()
  await expect(guest.getByLabel("Workspace role: visitor")).toBeVisible()
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  await host.getByRole("list", { name: "Mesh members" }).getByRole("button").filter({ hasText: "visitor" }).click()
  await host.getByRole("button", { name: "Make editor", exact: true }).click()
  await expect(guest.getByLabel("Workspace role: editor")).toBeVisible({ timeout: 20000 })
  await guest.reload()
  await expect(guest.getByLabel("Workspace role: editor")).toBeVisible()
  await expect(guest.getByRole("button", { name: /Add lead to/ }).first()).toBeVisible()
  await host.getByRole("button", { name: "Remove device", exact: true }).click()
  const confirmation = page.getByRole("dialog", { name: "Confirm device removal" })
  await expect(confirmation.getByLabel("Only this workspace")).toBeChecked()
  await confirmation.getByRole("button", { name: "Cancel", exact: true }).click()
  await expect(guest.getByLabel("Workspace role: editor")).toBeVisible()
  await host.getByRole("button", { name: "Remove device", exact: true }).click()
  await confirmation.getByLabel("All workspaces I can manage for this device").check()
  await expect(confirmation.getByRole("listitem")).toHaveCount(1)
  await expect(confirmation.locator("..")).toHaveCSS("opacity", "1")
  await page.screenshot({ animations: "disabled", path: testInfo.outputPath("device-removal-confirmation.png") })
  await confirmation.getByRole("button", { name: "Confirm removal", exact: true }).click()
  await expect(confirmation).toHaveCount(0)
  await expect(guest.getByLabel("Workspace role: visitor")).toBeVisible({ timeout: 20000 })
  await expect(guest.getByRole("button", { name: /Add lead to/ })).toHaveCount(0)
})
