import { expect, test } from "./support/coverage"
import { ensureJobSearchWorkspace } from "./support/workspaces"

test("owner promotes a visitor, then removes only their device through an explicit scope confirmation", async ({ page, browser }, testInfo) => {
  test.setTimeout(90000)
  await page.goto("/")
  await ensureJobSearchWorkspace(page)
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  const host = page.getByRole("dialog", { name: "Device sync" })
  await host.getByRole("button", { name: "Add someone" }).click()
  await host.getByRole("button", { name: "Generate link" }).click()
  const context = await browser.newContext()
  const guest = await context.newPage()
  await guest.goto(await host.getByLabel("Pairing link").inputValue())
  const guestDialog = guest.getByRole("dialog", { name: "Device sync" })
  await guestDialog.getByRole("button", { name: "Accept and join" }).click()
  await host.getByRole("button", { name: "Approve access" }).click()
  await expect(guestDialog.getByText(/Connected to/)).toBeVisible({ timeout: 30000 })
  await guestDialog.getByRole("button", { name: "Close", exact: true }).first().click()
  await host.getByRole("button", { name: "Close", exact: true }).first().click()
  await expect(guest.getByLabel("Workspace role: visitor")).toBeVisible()
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  await host.getByRole("list", { name: "Mesh members" }).getByRole("button").filter({ hasText: "visitor" }).click()
  await host.getByRole("button", { name: "Make editor", exact: true }).click()
  await expect(guest.getByLabel("Workspace role: editor")).toBeVisible({ timeout: 20000 })
  await guest.reload()
  await expect(guest.getByLabel("Workspace role: editor")).toBeVisible()
  await expect(guest.getByRole("button", { name: /Add lead to/ }).first()).toBeVisible()
  await host.getByRole("button", { name: "Remove device", exact: true }).click()
  const confirmation = page.getByRole("dialog", { name: "Confirm device removal" })
  await expect(confirmation.getByLabel("Only this workspace")).toBeChecked()
  await confirmation.getByRole("button", { name: "Cancel", exact: true }).click()
  await expect(guest.getByLabel("Workspace role: editor")).toBeVisible()
  await host.getByRole("button", { name: "Remove device", exact: true }).click()
  await confirmation.getByLabel("All workspaces I can manage for this device").check()
  await expect(confirmation.getByRole("listitem")).toHaveCount(1)
  await expect(confirmation.locator("..")).toHaveCSS("opacity", "1")
  await page.screenshot({ animations: "disabled", path: testInfo.outputPath("device-removal-confirmation.png") })
  await confirmation.getByRole("button", { name: "Confirm removal", exact: true }).click()
  await expect(confirmation).toHaveCount(0)
  await expect(guest.getByLabel("Workspace role: visitor")).toBeVisible({ timeout: 20000 })
  await expect(guest.getByRole("button", { name: /Add lead to/ })).toHaveCount(0)

  // Given a revoked member device, another invitation must offer an explicit recovery path.
  await host.getByRole("button", { name: "Close", exact: true }).first().click()
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  await host.getByRole("button", { name: "Add someone", exact: true }).click()
  await host.getByRole("button", { name: "Generate link", exact: true }).click()
  await guest.goto(await host.getByLabel("Pairing link").inputValue())
  const reconnect = guestDialog.getByRole("region", { name: "Confirm device reconnection" })
  await expect(reconnect).toContainText("owner must approve")
  await expect(reconnect).toHaveCSS("border-top-width", "2px")
  await guest.screenshot({ animations: "disabled", path: testInfo.outputPath("device-reconnection.png") })
  await expect(host.getByRole("button", { name: "Approve access", exact: true })).toHaveCount(0)

  // When cancelling reconnection, access stays revoked and no request reaches the owner.
  await reconnect.getByRole("button", { name: "Cancel", exact: true }).click()
  await expect(reconnect).toBeHidden()
  await expect(host.getByRole("button", { name: "Approve access", exact: true })).toHaveCount(0)
  await expect(guest.getByRole("button", { name: /Add lead to/ })).toHaveCount(0)

  // Then one guest confirmation and one owner approval reconnect the renewed device.
  await guestDialog.getByRole("button", { name: "Reconnect this device", exact: true }).click()
  await reconnect.getByRole("button", { name: "Confirm reconnection", exact: true }).click()
  await expect(host.getByRole("button", { name: "Approve access", exact: true })).toBeVisible({ timeout: 30000 })
  await expect(guestDialog.getByRole("status")).toContainText("Waiting for owner approval")
  await host.getByRole("button", { name: "Approve access", exact: true }).click()
  await expect(guestDialog.getByText(/Connected to/)).toBeVisible({ timeout: 30000 })
  await expect(guest.getByLabel("Mesh connected", { exact: true })).toBeVisible()
  await expect(guest.getByLabel("Mesh offline", { exact: true })).toHaveCount(0)
  await guestDialog.getByRole("button", { name: "Close", exact: true }).first().click()
  await guest.getByRole("button", { name: "Sync", exact: true }).click()
  await expect(guestDialog.getByRole("button", { name: "Stop live sync", exact: true })).toBeVisible()
  await guest.reload()
  await expect(guest.getByLabel("Workspace role: visitor")).toBeVisible()
  await guest.getByRole("button", { name: "Sync", exact: true }).click()
  await expect(guestDialog.getByRole("alert")).toHaveCount(0)
  await context.close()
})
