import { expect, test, type Locator } from "./support/coverage"
import { ensureJobSearchWorkspace } from "./support/workspaces"

async function angle(locator: Locator) {
  return locator.evaluate(element => {
    const matrix = new DOMMatrix(getComputedStyle(element).transform)
    return Math.atan2(matrix.b, matrix.a) * 180 / Math.PI
  })
}

test("Given paper buttons and cards, when hovered, then rotation is visible and clicking still opens the card", async ({ page }, info) => {
  await page.emulateMedia({ reducedMotion: "no-preference" })
  await page.goto("/")
  await page.getByRole("button", { name: "Add item to To do", exact: true }).click()
  const form = page.getByRole("dialog", { name: "Item details", exact: true })
  await form.getByLabel("Title *").fill("Paper card")
  const save = form.getByRole("button", { name: "Save item", exact: true })
  await save.hover()
  await expect.poll(async () => Math.abs(await angle(save))).toBeGreaterThan(2)
  await save.click()
  const card = page.locator(".lead-card").filter({ hasText: "Paper card" })
  await card.hover()
  await expect.poll(async () => Math.abs(await angle(card))).toBeGreaterThan(1)
  await page.screenshot({ path: info.outputPath("paper-card-hover.png") })
  await card.getByRole("button", { name: "Open Paper card", exact: true }).click()
  await expect(page.getByRole("dialog", { name: "Item overview", exact: true })).toBeVisible()

  await page.getByRole("button", { name: "Close detail", exact: true }).click()
  await page.emulateMedia({ reducedMotion: "reduce" })
  await card.hover()
  expect(await angle(card)).toBe(0)
})

test("Given archive, when expanded and collapsed, then open archive keeps strokes and folded columns retain their category colors and closed borders", async ({ page }, info) => {
  await page.setViewportSize({ width: 1920, height: 950 })
  await page.goto("/")
  await ensureJobSearchWorkspace(page)
  const archive = page.getByRole("region", { name: "Archive", exact: true })
  const closed = archive.getByRole("button", { name: "Open Archive with 0 cards", exact: true })
  await expect(closed).toHaveCSS("color", "rgb(23, 23, 23)")
  await expect(closed).toHaveCSS("background-color", "rgba(0, 0, 0, 0)")
  expect(await closed.evaluate(element => getComputedStyle(element, "::before").maskImage)).toBe("none")
  await expect(archive).toHaveCSS("border-top-width", "2px")
  await expect(archive).toHaveCSS("border-bottom-width", "2px")
  await expect(archive).toHaveCSS("border-image-source", "none")
  await expect.poll(async () => (await archive.boundingBox())!.width).toBe(64)
  await expect(archive.locator(".column-paper")).toHaveCSS("opacity", "1")
  const archivePaper = await archive.locator(".column-fold-cover").evaluate(element => getComputedStyle(element).backgroundColor)
  const canvas = await page.locator("body").evaluate(element => getComputedStyle(element).backgroundColor)
  expect(archivePaper).not.toBe(canvas)
  expect(await archive.locator(".column-fold-cover").evaluate(element => getComputedStyle(element, "::before").maskImage)).toContain("column-hatch.svg")
  await expect(archive.locator(".column-spine-mark")).toHaveCount(0)
  const hatchOpacity = () => archive.locator(".column-fold-cover").evaluate(element => Number(getComputedStyle(element, "::before").opacity))
  await closed.hover()
  await expect.poll(hatchOpacity).toBe(.58)
  await closed.click()
  await expect(archive.getByText("No leads", { exact: true })).toBeVisible()
  const header = archive.locator(".column-header")
  await expect(header).toHaveCSS("color", "rgb(23, 23, 23)")
  expect(await header.evaluate(element => getComputedStyle(element, "::before").maskImage)).toContain("column-hatch.svg")
  await page.screenshot({ path: info.outputPath("archive-crossed.png") })
  await archive.getByRole("button", { name: "Collapse Archive", exact: true }).click()
  await expect(closed).toBeVisible()
  await expect(closed).toHaveCSS("background-color", "rgba(0, 0, 0, 0)")
  expect(await closed.evaluate(element => getComputedStyle(element, "::before").maskImage)).toBe("none")
  const rejected = page.getByRole("region", { name: "Rejected", exact: true })
  await rejected.getByRole("button", { name: "Collapse Rejected", exact: true }).click()
  await expect.poll(async () => (await rejected.boundingBox())!.width).toBe(64)
  const rejectedPaper = await rejected.locator(".column-fold-cover").evaluate(element => getComputedStyle(element).backgroundColor)
  expect(rejectedPaper).not.toBe(archivePaper)
  await expect(rejected).toHaveCSS("border-top-width", "2px")
  await expect(rejected).toHaveCSS("border-image-source", "none")
  await page.mouse.move(0, 0)
  await page.screenshot({ path: info.outputPath("folded-spines.png") })
  await page.setViewportSize({ width: 390, height: 844 })
  await closed.scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath("folded-spines-mobile.png") })
  await closed.focus()
  await page.keyboard.press("Enter")
  await expect(archive.getByText("No leads", { exact: true })).toBeVisible()
})

test("Given local device details and recovery words, when viewed or restore fails, then technical text remains readable in Fira Code", async ({ page }, info) => {
  await page.goto("/")
  await ensureJobSearchWorkspace(page)
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  const sync = page.getByRole("dialog", { name: "Device sync", exact: true })
  await expect(sync).toBeVisible()
  const members = sync.getByRole("list", { name: "Mesh members" })
  const memberButtons = members.getByRole("button")
  // The current device loads asynchronously even without connected peers.
  await expect(memberButtons.first()).toBeVisible()
  await memberButtons.first().click()
  const deviceId = sync.locator(".mesh-device-head code")
  await expect(deviceId).toHaveCSS("font-family", /Fira Code/)
  await expect(deviceId).toHaveCSS("font-variant-ligatures", "none")
  await sync.getByRole("button", { name: "Close", exact: true }).click()
  await page.getByRole("button", { name: "Settings", exact: true }).click()
  const settings = page.getByRole("dialog", { name: "Settings", exact: true })
  await settings.getByRole("tab", { name: "Identity", exact: true }).click()
  await settings.getByRole("button", { name: "Recovery backup", exact: true }).click()
  const recovery = page.getByRole("dialog", { name: "Identity recovery", exact: true })
  const words = recovery.getByRole("textbox", { name: "Recovery words", exact: true })
  await words.fill("IIl10 O0 abcdef0123456789")
  await expect(words).toHaveCSS("font-family", /Fira Code/)
  const loadedFonts = await page.evaluate(async () => (await document.fonts.load(
    '400 15px "Fira Code"', "IIl10 O0 abcdef0123456789",
  )).map(font => font.status))
  expect(loadedFonts.length).toBeGreaterThan(0)
  expect(loadedFonts.every(status => status === "loaded")).toBe(true)
  expect(await page.evaluate(() => document.fonts.check('400 15px "Fira Code"'))).toBe(true)
  const restore = recovery.getByRole("button", { name: "Restore identity", exact: true })
  await restore.hover({ force: true })
  expect(await angle(restore)).toBe(0)
  await recovery.getByRole("checkbox").check()
  await restore.click()
  await expect(recovery.getByRole("alert")).toBeVisible()
  await expect(words).toHaveValue("IIl10 O0 abcdef0123456789")
  await page.screenshot({ path: info.outputPath("technical-type-failure.png") })
})
