import { expect, test } from "./support/coverage"
import { ensureJobSearchWorkspace } from "./support/workspaces"

for (const width of [390, 1440]) {
  test(`Given a ${width}px board, when a select opens and a long chat message scrolls, then paper controls and complete message frames remain usable`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto("/")
    await ensureJobSearchWorkspace(page)
    if (width < 768) await page.getByRole("button", { name: "Filters", exact: true }).click()
    const workMode = page.getByRole("group", { name: "Filters" }).getByRole("combobox", { name: "Work mode", exact: true })
    const remote = workMode.getByRole("option", { name: "Remote", exact: true })
    const remoteId = await remote.getAttribute("value")
    const customPicker = await page.evaluate(() => CSS.supports("appearance", "base-select"))
    await expect(workMode).toHaveCSS("appearance", customPicker ? "base-select" : "auto")
    if (customPicker) {
      await workMode.click()
      await expect(remote).toBeVisible()
      await page.screenshot({ path: info.outputPath(`paper-select-${width}.png`), animations: "disabled" })
      await remote.click()
    } else {
      await workMode.selectOption(remoteId!)
      await page.screenshot({ path: info.outputPath(`paper-select-${width}.png`), animations: "disabled" })
    }
    await expect(workMode).toHaveValue(remoteId!)
    await workMode.focus()
    if (customPicker) {
      await page.keyboard.press("Space")
      await page.keyboard.press("Escape")
    }
    await expect(workMode).toHaveValue(remoteId!)
    await expect(workMode).toBeFocused()
    await workMode.selectOption({ label: "Any" })
    await page.getByRole("button", { name: "Workspace chat", exact: true }).filter({ visible: true }).click()
    const chat = page.getByRole("dialog", { name: "Workspace chat", exact: true })
    const draft = chat.getByRole("textbox", { name: "Message", exact: true })
    const send = chat.getByRole("button", { name: "Send message" })
    await expect(send).toBeDisabled()
    await draft.fill(Array.from({ length: 24 }, (_, index) => `Paragraph ${index + 1}. Explain your work, the result and what improved.`).join("\n\n"))
    await send.click()
    await expect(chat.locator(".chat-message-pending")).toHaveCount(0)
    const log = chat.getByRole("log", { name: "Messages" })
    const message = log.locator(".chat-message-item").first()
    await expect(message.locator(".markdown-content")).toBeVisible()
    expect(await message.evaluate(element => element.scrollHeight <= element.clientHeight + 1)).toBe(true)
    expect(await log.evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true)
    await expect.poll(() => log.evaluate(element => Math.abs(element.scrollHeight - element.scrollTop - element.clientHeight))).toBeLessThan(2)
    await log.evaluate(element => { element.scrollTo({ top: 0, behavior: "instant" }) })
    await expect.poll(() => log.evaluate(element => element.scrollTop)).toBe(0)
    const start = await message.boundingBox()
    const bounds = await log.boundingBox()
    expect(start!.y).toBeGreaterThan(bounds!.y + 5)
    await chat.screenshot({ path: info.outputPath(`chat-start-${width}.png`) })
    await log.evaluate(element => { element.scrollTo({ top: element.scrollHeight, behavior: "instant" }) })
    await expect.poll(() => log.evaluate(element => Math.abs(element.scrollHeight - element.scrollTop - element.clientHeight))).toBeLessThan(2)
    const end = await message.boundingBox()
    expect(end!.y + end!.height).toBeLessThan(bounds!.y + bounds!.height - 5)
    await chat.screenshot({ path: info.outputPath(`chat-end-${width}.png`) })
    expect(await chat.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    const windowBody = chat.locator(".spatial-body")
    expect(await windowBody.evaluate(element => element.scrollHeight <= element.clientHeight + 1)).toBe(true)
    await expect(draft).toBeVisible()
    await expect(send).toBeDisabled()
  })
}
