import { expect, test } from "./support/coverage"

for (const width of [1280, 390]) test(`Given Settings at ${width}px, when switching scope, then profile, workspace and connections stay separate`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto("/")
  if (width < 640) await page.getByRole("button", { name: "Menu", exact: true }).click()
  await page.getByRole("button", { name: "Settings", exact: true }).filter({ visible: true }).click()
  if (width < 640) await expect(page.getByRole("dialog", { name: "Navigation menu" })).toHaveCount(0)
  const settings = page.getByRole("dialog", { name: "Settings", exact: true })
  await expect(settings.getByRole("tablist", { name: "Settings views" }).getByRole("tab")).toHaveText(["Identity", "Workspace", "Connections"])
  await expect(settings.getByLabel("Name", { exact: true })).toBeVisible()
  await expect(settings.getByLabel("Choose photo")).toBeAttached()
  await expect(settings.getByLabel("Intake URL")).toHaveCount(0)
  await expect(settings.getByRole("tab", { name: "JSON", exact: true })).toHaveCount(0)
  await expect(settings).toHaveCSS("transform", "none")
  await expect(settings.locator("..")).toHaveCSS("opacity", "1")
  await page.screenshot({ animations: "disabled", path: info.outputPath(`identity-${width}.png`) })
  await settings.getByRole("tab", { name: "Workspace", exact: true }).click()
  await expect(settings.getByRole("region", { name: "Identity photo" })).toHaveCount(0)
  await expect(settings.getByLabel("Workspace settings JSON")).toBeHidden()
  await page.screenshot({ animations: "disabled", path: info.outputPath(`workspace-${width}.png`) })
  await settings.getByText("Advanced configuration", { exact: true }).click()
  await expect(settings.getByLabel("Workspace settings JSON")).toBeVisible()
  await settings.getByRole("tab", { name: "Connections", exact: true }).click()
  await expect(settings.getByRole("button", { name: "Participants and devices", exact: true })).toBeVisible()
  await expect(settings.getByRole("button", { name: "Back up or move workspace", exact: true })).toBeVisible()
  await expect(settings.getByText("Approve job automation", { exact: true })).toHaveCount(0)
  await page.screenshot({ animations: "disabled", path: info.outputPath(`connections-${width}.png`) })
  await settings.getByRole("button", { name: "Back up or move workspace", exact: true }).click()
  const sync = page.getByRole("dialog", { name: "Device sync" })
  await expect(settings).toHaveCount(0)
  await expect(sync.getByRole("tab", { name: "Backups", exact: true })).toHaveAttribute("aria-selected", "true")
  await expect(sync.getByRole("button", { name: "Export .tincanban", exact: true })).toBeVisible()
  await expect(sync.getByRole("region", { name: "Ownership succession" })).toBeHidden()
})

test("Given a job-search workspace, when keyboard moves between settings and board sections, then focus and visible content follow selection", async ({ page }) => {
  const { ensureJobSearchWorkspace } = await import("./support/workspaces")
  await page.goto("/")
  await ensureJobSearchWorkspace(page)
  await page.getByRole("button", { name: "Settings", exact: true }).click()
  const settings = page.getByRole("dialog", { name: "Settings", exact: true })
  await settings.getByRole("tab", { name: "Identity", exact: true }).focus()
  await page.keyboard.press("ArrowRight")
  await expect(settings.getByRole("tab", { name: "Workspace", exact: true })).toBeFocused()
  await expect(settings.getByRole("tab", { name: "Document templates", exact: true })).toBeVisible()
  await settings.getByRole("tab", { name: "Document templates", exact: true }).focus()
  await page.keyboard.press("ArrowRight")
  await expect(settings.getByRole("tab", { name: "Priority rules", exact: true })).toBeFocused()
  await expect(settings.getByRole("tabpanel", { name: "Priority rules", exact: true })).toBeVisible()
  await expect(settings.getByRole("tabpanel", { name: "Document templates", exact: true })).toHaveCount(0)
  await page.keyboard.press("Home")
  await expect(settings.getByRole("tab", { name: "Document templates", exact: true })).toBeFocused()
  await expect(settings.getByRole("tabpanel", { name: "Document templates", exact: true })).toBeVisible()
})
