import { expect, test } from "./support/coverage"

for (const width of [1280, 390]) test(`Given Device sync at ${width}px, when switching tasks, then each tab exposes only its relevant controls`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto("/")
  await expect(page.getByLabel("Workspace role: owner")).toBeVisible()
  if (width < 640) {
    await page.getByRole("button", { name: "Menu", exact: true }).click()
    await page.getByRole("button", { name: "Sync, import & export", exact: true }).click()
  } else await page.getByRole("button", { name: "Sync", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "Device sync" })
  const participants = dialog.getByRole("tab", { name: "Participants", exact: true })
  await expect(participants).toHaveAttribute("aria-selected", "true")
  await expect(dialog.getByRole("list", { name: "Mesh members" })).toBeVisible()
  await expect(dialog.getByRole("button", { name: "Stop live sync", exact: true })).toBeHidden()
  await expect(dialog.getByRole("button", { name: "Leave mesh", exact: true })).toBeHidden()
  await dialog.getByText("Advanced", { exact: true }).click()
  await expect(dialog.getByRole("button", { name: "Stop live sync", exact: true })).toBeVisible()
  await participants.focus()
  await page.keyboard.press("ArrowRight")
  await expect(dialog.getByRole("tab", { name: "Rusty", exact: true })).toBeFocused()
  await expect(dialog.getByRole("tabpanel", { name: "Rusty", exact: true })).toBeVisible()
  await expect(dialog.locator(".mesh-connection-summary")).toBeHidden()
  await expect(dialog.getByRole("list", { name: "Mesh members" })).toBeHidden()
  await expect(dialog.getByLabel("Address", { exact: true })).toBeHidden()
  await expect(dialog.getByRole("button", { name: "Add Rusty", exact: true })).toBeVisible()
  await dialog.getByRole("tab", { name: "Backups", exact: true }).click()
  await expect(dialog.getByRole("region", { name: "Ownership succession" })).toHaveCount(0)
  await expect(dialog.getByRole("button", { name: "Export .tincanban", exact: true })).toBeVisible()
  await expect(dialog.getByRole("button", { name: "Import as new board", exact: true })).toBeVisible()
  await expect(dialog.getByRole("button", { name: "Add someone", exact: true })).toBeHidden()
  const tabs = dialog.getByRole("tablist", { name: "Sync tasks" })
  expect(await tabs.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath(`sync-recovery-${width}.png`) })
})

test("Given Rusty is unavailable, when connecting from its tab, then pending and failure stay local to Rusty", async ({ page }) => {
  let release = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route("https://rusty.invalid/**", async route => { await gate; await route.abort() })
  await page.goto("/")
  await expect(page.getByLabel("Workspace role: owner")).toBeVisible()
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  const dialog = page.getByRole("dialog", { name: "Device sync" })
  await dialog.getByRole("tab", { name: "Rusty", exact: true }).click()
  const panel = dialog.getByRole("region", { name: "Rusty", exact: true })
  await panel.getByRole("button", { name: "Add Rusty", exact: true }).click()
  await panel.getByLabel("Address", { exact: true }).fill("https://rusty.invalid")
  await panel.getByRole("button", { name: "Connect", exact: true }).click()
  await expect(panel.getByRole("status")).toContainText("Working")
  await expect(panel.getByRole("button", { name: "Connect", exact: true })).toBeDisabled()
  release()
  await expect(panel.getByRole("alert")).toBeVisible()
  await expect(panel.getByRole("button", { name: "Connect", exact: true })).toBeEnabled()
  await dialog.getByRole("tab", { name: "Participants", exact: true }).click()
  await expect(dialog.getByRole("list", { name: "Mesh members" })).toBeVisible()
  await expect(panel.getByRole("alert")).toBeHidden()
})
