import { expect, test } from "./support/coverage"

for (const width of [1440, 390]) {
  test(`Given a ${width}px viewport, when creating a configured board, then its name, columns, required fields, and select options appear in the item form`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto("/")
    await page.getByRole("button", { name: "Open workspaces" }).click()
    await page.getByRole("button", { name: "New workspace" }).click()
    const dialog = page.getByRole("dialog", { name: "Create workspace" })
    await dialog.getByLabel("Title", { exact: true }).fill("Reading List")
    await dialog.getByRole("button", { name: "Customize board" }).click()
    await dialog.getByLabel("Item name", { exact: true }).waitFor()
    await dialog.getByLabel("Item name", { exact: true }).fill("book")
    await dialog.getByLabel("Column 1", { exact: true }).fill("Queue")
    await dialog.getByLabel("Column 2", { exact: true }).fill("Reading")
    await dialog.getByLabel("Column 3", { exact: true }).fill("Finished")
    await dialog.getByRole("button", { name: "Move column 1 down" }).click()
    await page.screenshot({ animations: "disabled", path: testInfo.outputPath(`board-config-top-${width}.png`) })
    await dialog.getByRole("button", { name: "Add field" }).click()
    const nameField = dialog.getByRole("group", { name: "Field 1" })
    await nameField.getByLabel("Field name").fill("Author")
    await nameField.getByLabel("Field type").selectOption("text")
    await nameField.getByLabel("Required").check()
    await dialog.getByRole("button", { name: "Add field" }).click()
    const genreField = dialog.getByRole("group", { name: "Field 2" })
    await genreField.getByLabel("Field name").fill("Genre")
    await genreField.getByLabel("Field type").selectOption("select")
    await genreField.getByLabel("Required").check()
    await genreField.getByRole("button", { name: "Edit options" }).click()
    await genreField.getByRole("button", { name: "Add option" }).click()
    await genreField.getByLabel("Option 1", { exact: true }).fill("Fiction")
    await genreField.getByRole("button", { name: "Add option" }).click()
    await genreField.getByLabel("Option 2", { exact: true }).fill("History")
    await expect(dialog.getByRole("button", { name: "Customize board" })).toContainText("book, 3 columns, 2 fields")
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await expect(dialog.getByRole("button", { name: "Create", exact: true })).toBeVisible()
    await page.screenshot({ animations: "disabled", path: testInfo.outputPath(`board-config-${width}.png`) })
    await dialog.getByRole("button", { name: "Customize board" }).click()
    await expect(dialog.getByRole("button", { name: "Customize board" })).toHaveAttribute("aria-expanded", "false")
    await dialog.getByRole("button", { name: "Create", exact: true }).click()

    await expect(page.getByRole("heading", { name: "TINCANBAN // Reading List", exact: true })).toBeVisible()
    for (const column of ["Queue", "Reading", "Finished"]) {
      await expect(page.getByRole("region", { name: column, exact: true })).toBeVisible()
    }
    await page.getByRole("button", { name: /Add book to/ }).first().click()
    const item = page.getByRole("dialog", { name: "Item details" })
    await expect(item.getByRole("heading", { name: "Book details" })).toBeVisible()
    await expect(item.getByLabel("Author *")).toBeVisible()
    await expect(item.getByLabel("Genre")).toBeVisible()
    await expect(item.getByLabel("Genre").getByRole("option", { name: "Fiction" })).toHaveCount(1)
    await expect(item.getByLabel("Genre").getByRole("option", { name: "History" })).toHaveCount(1)
    await item.getByLabel("Title *").fill("The Left Hand of Darkness")
    await item.getByLabel("Genre").selectOption({ label: "Fiction" })
    await item.getByRole("button", { name: "Save item" }).click()
    await expect(item.getByRole("alert")).toContainText("Author is required")
    await item.getByLabel("Author *").fill("Ursula K. Le Guin")
    await item.getByLabel("Genre").selectOption("")
    await item.getByRole("button", { name: "Save item" }).click()
    await expect(item.getByRole("alert")).toContainText("Genre is required")
    await item.getByLabel("Genre").selectOption({ label: "Fiction" })
    await item.getByRole("button", { name: "Save item" }).click()
    await expect(page.getByRole("button", { name: "Open The Left Hand of Darkness" })).toBeVisible()
    await page.reload()
    await expect(page.getByRole("region", { name: "Finished", exact: true })).toBeVisible()
    await page.getByRole("button", { name: /Add book to/ }).first().click()
    const afterReload = page.getByRole("dialog", { name: "Item details" })
    await expect(afterReload.getByLabel("Author *")).toBeVisible()
    await expect(afterReload.getByLabel("Genre").getByRole("option", { name: "History" })).toHaveCount(1)
    await expect(afterReload.getByLabel("Status *").locator("option")).toHaveText(["Reading", "Queue", "Finished"])
  })
}

test("Given edited configuration, when preset changes, then draft stays intact; invalid and failed saves keep draft for retry", async ({ page }) => {
  await page.goto("/")
  await page.getByRole("button", { name: "Open workspaces" }).click()
  await page.getByRole("button", { name: "New workspace" }).click()
  const dialog = page.getByRole("dialog", { name: "Create workspace" })
  await dialog.getByLabel("Title", { exact: true }).fill("Draft board")
  await dialog.getByRole("button", { name: "Customize board" }).click()
  await dialog.getByLabel("Column 1", { exact: true }).fill("Draft column")
  await dialog.getByRole("radio", { name: "Job search" }).check()
  await expect(dialog.getByLabel("Column 1", { exact: true })).toHaveValue("Draft column")
  await dialog.getByRole("radio", { name: "Blank board" }).check()
  await dialog.getByLabel("Column 1", { exact: true }).fill("")
  await dialog.getByRole("button", { name: "Create", exact: true }).click()
  await expect(dialog.getByRole("alert")).toContainText("Column title is required")
  await dialog.getByLabel("Column 1", { exact: true }).fill("Draft column")
  await dialog.getByRole("button", { name: "Customize board" }).click()
  await expect(dialog.getByRole("button", { name: "Customize board" })).toHaveAttribute("aria-expanded", "false")
  await page.evaluate(() => { (window as any).__TINCANBAN_INJECT_STORAGE_FAILURE__ = true })
  await dialog.getByRole("button", { name: "Create", exact: true }).click()
  await expect(dialog.getByRole("alert")).toContainText("Storage failure injected")
  await dialog.getByRole("button", { name: "Customize board" }).click()
  await expect(dialog.getByLabel("Column 1", { exact: true })).toHaveValue("Draft column")
  await expect(dialog.getByRole("button", { name: "Create", exact: true })).toBeEnabled()
  await page.evaluate(() => { delete (window as any).__TINCANBAN_INJECT_STORAGE_FAILURE__ })
  await dialog.getByRole("button", { name: "Create", exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole("region", { name: "Draft column", exact: true })).toBeVisible()
})

test("Given clean defaults or edited configuration, when presets change or reset is chosen, then changes happen only as requested", async ({ page }) => {
  await page.goto("/")
  await page.getByRole("button", { name: "Open workspaces" }).click()
  await page.getByRole("button", { name: "New workspace" }).click()
  const dialog = page.getByRole("dialog", { name: "Create workspace" })
  await dialog.getByRole("button", { name: "Customize board" }).click()
  await dialog.getByRole("radio", { name: "Job search" }).check()
  await expect(dialog.getByRole("button", { name: "Customize board" })).toContainText("lead, 6 columns, 10 fields")
  await dialog.getByRole("radio", { name: "Blank board" }).check()
  await expect(dialog.getByRole("button", { name: "Customize board" })).toContainText("item, 3 columns, 0 fields")
  await dialog.getByLabel("Column 1", { exact: true }).fill("Manual")
  await dialog.getByRole("radio", { name: "Job search" }).check()
  await expect(dialog.getByLabel("Column 1", { exact: true })).toHaveValue("Manual")
  await dialog.getByRole("button", { name: "Reset to Job search defaults" }).click()
  await expect(dialog.getByLabel("Column 1", { exact: true })).toHaveValue("Lead")
  await expect(dialog.getByRole("button", { name: "Customize board" })).toContainText("lead, 6 columns, 10 fields")
  await dialog.getByRole("radio", { name: "Blank board" }).check()
  await expect(dialog.getByLabel("Column 1", { exact: true })).toHaveValue("To do")
})

test("Given preset Archive column and a removed column, when the draft is created, then archive behavior stays intact without stale stage references", async ({ page }) => {
  await page.goto("/")
  await page.getByRole("button", { name: "Open workspaces" }).click()
  await page.getByRole("button", { name: "New workspace" }).click()
  const dialog = page.getByRole("dialog", { name: "Create workspace" })
  await dialog.getByLabel("Title", { exact: true }).fill("Custom jobs")
  await dialog.getByRole("radio", { name: "Job search" }).check()
  await dialog.getByRole("button", { name: "Customize board" }).click()
  await dialog.getByLabel("Column 1", { exact: true }).waitFor()
  await dialog.getByRole("button", { name: "Remove column 2" }).click()
  await expect(dialog.getByRole("button", { name: "Customize board" })).toContainText("lead, 5 columns, 10 fields")
  await dialog.getByRole("button", { name: "Create", exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole("region", { name: "Lead", exact: true })).toBeVisible()
  await expect(page.getByRole("region", { name: "Applied", exact: true })).toHaveCount(0)
  const archive = page.getByRole("region", { name: "Archive", exact: true })
  await expect(archive).toBeVisible()
  await expect(archive.getByRole("button", { name: /Add lead to Archive/ })).toHaveCount(0)
})

test("Given initial workspace persistence is pending, when Create is submitted again, then duplicate submission stays disabled", async ({ page }) => {
  await page.goto("/")
  await page.getByRole("button", { name: "Open workspaces" }).click()
  await page.getByRole("button", { name: "New workspace" }).click()
  const dialog = page.getByRole("dialog", { name: "Create workspace" })
  await dialog.getByLabel("Title", { exact: true }).fill("One board")
  await dialog.getByRole("button", { name: "Customize board" }).click()
  await dialog.getByLabel("Item name", { exact: true }).fill("task")
  await page.evaluate(async () => {
    const gate: { reached: boolean; release?: () => void } = { reached: false }
    ;(window as any).__testStorageGate = gate
    const storage = await import("/src/storage.ts")
    const prototype = storage.WorkspaceStorage.prototype as any
    const save = prototype.commitWorkspace
    prototype.commitWorkspace = async function (...args: any[]) {
      gate.reached = true
      await new Promise<void>(resolve => { gate.release = resolve })
      return save.apply(this, args)
    }
  })
  await dialog.locator("form").evaluate(form => {
    (form as HTMLFormElement).requestSubmit()
    ;(form as HTMLFormElement).requestSubmit()
  })
  await expect.poll(() => page.evaluate(() => (window as any).__testStorageGate?.reached)).toBe(true)
  await expect(dialog.getByRole("button", { name: "Creating…" })).toBeDisabled()
  await expect(dialog.getByRole("button", { name: "Create", exact: true })).toHaveCount(0)
  await expect(dialog.getByLabel("Title", { exact: true })).toBeDisabled()
  await expect(dialog.getByRole("radio", { name: "Job search" })).toBeDisabled()
  await page.evaluate(() => { (window as any).__testStorageGate.release() })
  await expect(dialog).toBeHidden()
  await page.getByRole("button", { name: "Open workspaces" }).click()
  await expect(page.getByRole("dialog", { name: "Workspaces" }).locator(".workspace-item", { hasText: "One board" })).toHaveCount(1)
})
