import { expect, test, type Page } from "@playwright/test"

async function addLead(page: Page, company: string) {
  await page.getByRole("button", { name: /Add lead to/ }).first().click()
  await page.getByLabel("Company *").fill(company)
  await page.getByLabel("Role *").fill("Engineer")
  await page.getByRole("button", { name: "Create item" }).click()
  await page.getByRole("button", { name: "Close detail" }).click()
}

test("Given independent devices without a signaling API, when a workspace invitation is accepted, then saved cards arrive and edits sync both ways", async ({ browser, page }) => {
  test.setTimeout(90_000)
  await page.route("**/api/sync-signal**", route => route.fulfill({ status: 404 }))
  const guestContext = await browser.newContext()
  await guestContext.route("**/api/sync-signal**", route => route.fulfill({ status: 404 }))
  const guest = await guestContext.newPage()
  try {
    await page.goto("/")
    await addLead(page, "Host card")
    await page.getByRole("button", { name: "Sync", exact: true }).click()
    const hostDialog = page.getByRole("dialog", { name: "Device sync" })
    await hostDialog.getByRole("button", { name: "Generate link" }).click()
    const invite = await hostDialog.getByLabel("Pairing link").inputValue()
    await guest.goto(invite)
    const guestDialog = guest.getByRole("dialog", { name: "Device sync" })
    await guestDialog.getByRole("button", { name: "Accept and join" }).click()
    await page.getByLabel("Participant role").selectOption("editor")
    await page.getByRole("button", { name: "Approve access" }).click()
    await expect(guestDialog.getByText("Connected to Job search")).toBeVisible({ timeout: 25_000 })
    await guestDialog.getByRole("button", { name: "Close", exact: true }).first().click()
    await expect(guest.getByRole("button", { name: "Open Host card — Engineer" })).toBeVisible()
    await expect(guest).toHaveURL(invite)
    await hostDialog.getByRole("button", { name: "Close", exact: true }).first().click()
    await page.getByRole("button", { name: "Sync", exact: true }).click()
    await hostDialog.getByRole("button", { name: "Invite peers", exact: true }).click()
    await expect(hostDialog.getByRole("button", { name: "Generate link" })).toBeEnabled()
    await hostDialog.getByRole("button", { name: "Close", exact: true }).first().click()
    await addLead(guest, "Guest card")
    await expect(page.getByRole("button", { name: "Open Guest card — Engineer" })).toBeVisible({ timeout: 10_000 })
    await addLead(page, "Later host card")
    await expect(guest.getByRole("button", { name: "Open Later host card — Engineer" })).toBeVisible({ timeout: 10_000 })
    await guestContext.setOffline(true)
    await expect(guest.locator(".local-state").first()).toContainText("Reconnecting")
    await addLead(guest, "Saved offline")
    await addLead(page, "While guest offline")
    await guestContext.setOffline(false)
    await expect(page.getByRole("button", { name: "Open Saved offline — Engineer" })).toBeVisible({ timeout: 25_000 })
    await expect(guest.getByRole("button", { name: "Open While guest offline — Engineer" })).toBeVisible({ timeout: 25_000 })
    await expect(guest.locator(".local-state").first()).toContainText("Live")
    await expect(guest).toHaveURL(invite)
    await page.context().setOffline(true)
    await expect(page.locator(".local-state").first()).toContainText("Reconnecting")
    await addLead(page, "Host saved offline")
    await page.context().setOffline(false)
    await expect(guest.getByRole("button", { name: "Open Host saved offline — Engineer" })).toBeVisible({ timeout: 25_000 })
    await guest.goto("/")
    await expect(guest.getByRole("button", { name: "Open Host card — Engineer" })).toBeVisible()
    await expect(guest.getByRole("button", { name: "Open Guest card — Engineer" })).toBeVisible()
  } finally {
    await guestContext.close()
  }
})

test("Given no network before accepting, when the connection returns, then the same invitation completes without another click", async ({ browser, page }) => {
  test.setTimeout(45_000)
  await page.goto("/")
  await addLead(page, "Waiting for network")
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  const host = page.getByRole("dialog", { name: "Device sync" })
  await host.getByRole("button", { name: "Generate link" }).click()
  const invite = await host.getByLabel("Pairing link").inputValue()
  const context = await browser.newContext()
  try {
    const guest = await context.newPage()
    await guest.goto(invite)
    const dialog = guest.getByRole("dialog", { name: "Device sync" })
    await expect(dialog.getByRole("button", { name: "Accept and join" })).toBeVisible()
    await context.setOffline(true)
    await dialog.getByRole("button", { name: "Accept and join" }).click()
    await expect(dialog.getByRole("status")).toContainText("Reconnecting automatically")
    await context.setOffline(false)
    await page.getByLabel("Participant role").selectOption("editor")
    await page.getByRole("button", { name: "Approve access" }).click()
    await expect(dialog.getByText("Connected to Job search")).toBeVisible({ timeout: 25_000 })
    await dialog.getByRole("button", { name: "Close", exact: true }).first().click()
    await expect(guest.getByRole("button", { name: "Open Waiting for network — Engineer" })).toBeVisible()
    await expect(guest).toHaveURL(invite)
  } finally {
    await context.close()
  }
})

test("Given both devices have different populated workspaces with the same ID, when joining, then the local one is kept as a separate renamable workspace", async ({ browser, page }) => {
  test.setTimeout(60_000)
  await page.goto("/")
  await addLead(page, "Host workspace card")
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  const host = page.getByRole("dialog", { name: "Device sync" })
  await host.getByRole("button", { name: "Generate link" }).click()
  const invite = await host.getByLabel("Pairing link").inputValue()
  const context = await browser.newContext()
  try {
    const guest = await context.newPage()
    await guest.goto("/")
    await addLead(guest, "Guest local card")
    await guest.goto(invite)
    const dialog = guest.getByRole("dialog", { name: "Device sync" })
    await dialog.getByRole("button", { name: "Accept and join" }).click()
    await page.getByLabel("Participant role").selectOption("editor")
    await page.getByRole("button", { name: "Approve access" }).click()
    await expect(dialog.getByText("Connected to Job search")).toBeVisible({ timeout: 25_000 })
    await dialog.getByRole("button", { name: "Close", exact: true }).first().click()
    await expect(guest.getByRole("button", { name: "Open Host workspace card — Engineer" })).toBeVisible()
    await expect(guest.getByRole("button", { name: "Open Guest local card — Engineer" })).toHaveCount(0)
    await guest.getByRole("button", { name: "Open workspaces" }).click()
    const workspaces = guest.getByRole("dialog", { name: "Workspaces" })
    await expect(workspaces.getByRole("button", { name: /jobs/ })).toBeVisible()
    await expect(workspaces.getByRole("button", { name: /Job search \(local\)/ })).toBeVisible()
    await workspaces.getByRole("button", { name: /Job search \(local\)/ }).click()
    await expect(guest.getByRole("button", { name: "Open Guest local card — Engineer" })).toBeVisible()
    await expect(guest.getByRole("button", { name: "Open Host workspace card — Engineer" })).toHaveCount(0)
  } finally {
    await context.close()
  }
})

test("Given a storage failure on the receiving device, when joining, then it shows progress followed by an error and keeps the invitation", async ({ browser, page }) => {
  await page.goto("/")
  await addLead(page, "Must be saved")
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  const hostDialog = page.getByRole("dialog", { name: "Device sync" })
  await hostDialog.getByRole("button", { name: "Generate link" }).click()
  const invite = await hostDialog.getByLabel("Pairing link").inputValue()
  const guestContext = await browser.newContext()
  try {
    const guest = await guestContext.newPage()
    await guest.goto(invite)
    const dialog = guest.getByRole("dialog", { name: "Device sync" })
    await expect(dialog.getByRole("button", { name: "Accept and join" })).toBeVisible()
    await guest.evaluate(() => { (window as any).__MATCH_INJECT_STORAGE_FAILURE__ = true })
    await dialog.getByRole("button", { name: "Accept and join" }).click()
    await page.getByLabel("Participant role").selectOption("editor")
    await expect(dialog.getByRole("status")).toHaveText("Waiting for owner approval, then receiving workspaces… Keep both devices open.")
    await page.getByRole("button", { name: "Approve access" }).click()
    await expect(dialog.getByRole("alert")).toContainText(/Storage failure/i, { timeout: 25_000 })
    await expect(dialog.getByText(/Connected to/)).toHaveCount(0)
    await expect(guest).toHaveURL(invite)
    await guest.goto("/")
    await expect(guest.getByRole("button", { name: "Open Must be saved — Engineer" })).toHaveCount(0)
  } finally {
    await guestContext.close()
  }
})

test("Given three workspaces, when sharing A and B while viewing Private, then only selected documents arrive and stay independent", async ({ browser, page }) => {
  test.setTimeout(60_000)
  await page.route("**/api/sync-signal**", route => route.fulfill({ status: 404 }))
  await page.goto("/")
  for (const title of ["Shared A", "Shared B", "Private"]) {
    await page.getByRole("button", { name: "Open workspaces" }).click()
    await page.getByRole("button", { name: "New workspace" }).click()
    const create = page.getByRole("dialog", { name: "Create workspace" })
    await create.getByLabel("Title", { exact: true }).fill(title)
    await create.getByRole("button", { name: "Create", exact: true }).click()
    await page.getByRole("button", { name: /Add item to/ }).first().click()
    const item = page.getByRole("dialog", { name: "Item details" })
    await item.getByLabel("Title *").fill(`${title} card`)
    await item.getByRole("button", { name: "Save item" }).click()
  }
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  const hostDialog = page.getByRole("dialog", { name: "Device sync" })
  await hostDialog.getByLabel("Private", { exact: true }).uncheck()
  await hostDialog.getByLabel("Shared A", { exact: true }).check()
  await hostDialog.getByLabel("Shared B", { exact: true }).check()
  await hostDialog.getByRole("button", { name: "Generate link" }).click()
  const invite = await hostDialog.getByLabel("Pairing link").inputValue()
  const guestContext = await browser.newContext()
  await guestContext.route("**/api/sync-signal**", route => route.fulfill({ status: 404 }))
  try {
    const guest = await guestContext.newPage()
    await guest.goto(invite)
    const dialog = guest.getByRole("dialog", { name: "Device sync" })
    await dialog.getByRole("button", { name: "Accept and join" }).click()
    await page.getByLabel("Participant role").selectOption("editor")
    await page.getByRole("button", { name: "Approve access" }).click()
    await expect(dialog.getByText(/Connected to/)).toBeVisible({ timeout: 25_000 })
    await dialog.getByRole("button", { name: "Close", exact: true }).first().click()
    for (const title of ["Shared A", "Shared B"]) {
      await guest.getByRole("button", { name: "Open workspaces" }).click()
      const workspaces = guest.getByRole("dialog", { name: "Workspaces" })
      await expect(workspaces.getByRole("button", { name: "Private", exact: true })).toHaveCount(0)
      await workspaces.getByRole("button", { name: new RegExp(title) }).click()
      await expect(guest.getByRole("button", { name: `Open ${title} card`, exact: true })).toBeVisible()
      await expect(guest.getByRole("button", { name: "Open Private card", exact: true })).toHaveCount(0)
    }
    await hostDialog.getByRole("button", { name: "Close", exact: true }).first().click()
    await expect(page.getByRole("heading", { name: "MATCH // Private", exact: true })).toBeVisible()
  } finally {
    await guestContext.close()
  }
})

test("Given a sender without mesh support, when joining, then request an update before importing its tasks", async ({ browser, page }) => {
  test.setTimeout(45_000)
  await page.route("**/src/sync/useDeviceSync.ts", async route => {
    const response = await route.fetch()
    const source = await response.text()
    const legacy = source.replace(/meshWorkspaces: await durableMesh\?\.invitationPayload\([^\n]+/, "meshWorkspaces: undefined,")
    expect(legacy).not.toBe(source)
    await route.fulfill({ response, body: legacy })
  })
  await page.goto("/")
  await addLead(page, "Legacy sender task")
  await page.getByRole("button", { name: "Sync", exact: true }).click()
  const host = page.getByRole("dialog", { name: "Device sync" })
  await host.getByRole("button", { name: "Generate link" }).click()
  const invite = await host.getByLabel("Pairing link").inputValue()
  const context = await browser.newContext()
  try {
    const guest = await context.newPage()
    await guest.goto(invite)
    const dialog = guest.getByRole("dialog", { name: "Device sync" })
    await dialog.getByRole("button", { name: "Accept and join" }).click()
    await page.getByLabel("Participant role").selectOption("editor")
    await page.getByRole("button", { name: "Approve access" }).click()
    await expect(dialog.getByRole("alert")).toHaveText("The other device needs an update. Reload it and generate a new invitation.", { timeout: 25_000 })
    await dialog.getByRole("button", { name: "Dismiss" }).click()
    await expect(guest.getByRole("button", { name: "Open Legacy sender task — Engineer" })).toHaveCount(0)
  } finally {
    await context.close()
  }
})
